### ISSUE TITLE
INFO: pio lib search is going to be deprecated. 

### ISSUE THREAD

**Issue by ubaldot** [normen/vim-pio#11]
when I `$pio lib search` from the termial I get the following warning:

```
WARNING: This command is deprecated and will be removed in the next releases.
Please use `pio pkg search` instead.
```

**Comment by normen** [comment]
How is that relevant for the plugin?

**Comment by ubaldot** [comment]
I am not sure, but maybe `PIOAddLibrary` uses `pio lib search` in background? If not, then this issue can be closed ofc! :)

**Comment by normen** [comment]
Nah, it doesn't since a few versions, its still in the autocomplete and being recognized when used with `:PIO` though.
