### ISSUE TITLE
Adding Libraries

### ISSUE THREAD

**Issue by pyfb78** [normen/vim-pio#6]
How do we go to the next page when trying to add a new library to our project?
<img width="798" alt="Screenshot 2023-02-14 at 8 26 24 PM" src="https://user-images.githubusercontent.com/75864715/218930279-1bd54a1e-fa02-44ba-aa73-ae61711a6931.png">

**Comment by normen** [comment]
You'll have to make the search more specific or use completion for known names. You can also use the `:PIO` command to search in an interactive window.
