### ISSUE TITLE
Update documentation and README

### ISSUE THREAD

**Issue by proatgram** [normen/vim-pio#8]
Some of the vim-pio commands are not documented, and it's hard to tell how to use them and what arguments I need to pass to them. The first one I've encountered is `PIOUploadAndSerial`  which supposedly requires a global set for, although it is unclear what to set it to.
```
Error detected while processing function pio#PIOUploadAndSerial[3]..pio#PIOUpload:
line 1:
E121: Undefined variable: g:pio_serial_port
Error detected while processing function pio#PIOUploadAndSerial[5]..pio#PIOSerial:
line 1:
E121: Undefined variable: g:pio_serial_port
```
Some others that I have noticed don't have documentation for are `PIOUpload`, and `PIOChoosePort`.

**Comment by normen** [comment]
That whole stuff was added through a PR, I should have demanded documentation as well.. Dunno what exactly the point of those is given that the makefile allows for most of these things. Also the serial port should simply be read from the pio.ini really..
